wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710736779.0
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      - 77
      2:
      - 1
      - 41
      - 50
      - 55
      - 77
      3:
      - 13
      - 23
      4: 3.10.13
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
